#! /usr/bin/env bash
set -e
if [ -n "$DEBUG" ] ; then
  env
  set -x
fi
if [ -z "$SRB2WADDIR" ]; then
  export SRB2WADDIR=$APPDIR/usr/games/SRB2Kart
fi
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$APPDIR/usr/lib
exec $APPDIR/usr/bin/srb2kart "$@"
