name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build AppImage in Docker
        run: bash -ex build-everything.sh
      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "Latest Build"
          prerelease: false
          files: |
            srb2kart-x86_64.AppImage
            srb2kart-noassets-x86_64.AppImage
            srb2kart-moe-x86_64.AppImage
            srb2kart-moe-noassets-x86_64.AppImage
            *.AppImage.zsync
