name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Build AppImage in Docker
        run: bash -ex build-everything.sh

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: AppImage build
          path: |
            SRB2Kart-noassets-x86_64.AppImage
            SRB2Kart-x86_64.AppImage

  upload:
    name: Create release and upload artifacts
    needs:
      - build
    runs-on: ubuntu-18.04
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Inspect directory after downloading artifacts
        run: ls -alFR
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
            chmod +x pyuploadtool-x86_64.AppImage
            ./pyuploadtool-x86_64.AppImage **/SRB2Kart-x86_64.AppImage **/SRB2Kart-noassets-x86_64.AppImage
