name: Release
on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Build AppImage in Docker
        run: bash -ex build-everything.sh

      - uses: "marvinpinto/action-automatic-releases@v1.2.1"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "1.6"
          title: "Latest Build"
          prerelease: false
          files: |
            srb2kart-*.AppImage
            *.AppImage.zsync
