name: Testing
on:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Build AppImage in Docker
        run: bash -ex build-everything.sh

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: AppImage build
          path: |
            srb2kart*.AppImage
